# Generated by Django 2.1.5 on 2022-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=-1.0, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('bestseller', models.BooleanField(default=False)),
            ],
        ),
    ]
